services:

  tx-builder:
    build: ./services/tx-builder
    container_name: tx-builder
    environment:
      SERVICE_NAME: tx-builder
      NATS_URL: nats://nats:4222
      WORK_ROOT: /var/lib/btc-work/psbt-work

      DATABASE_URL: postgresql://user:pass@postgres:5432/btc

      MIDDLEWARE_URL: http://middleware:8080

      BITCOIN_NETWORK: regtest
      BITCOIND_RPC_URL: http://192.168.99.58:18443
      BITCOIND_RPC_USER: user
      BITCOIND_RPC_PASS: pass

      MAX_FEE_SATS: 5000
      MAX_FEE_RATE_SAT_VB: 50
      FEE_TOLERANCE_SATS: 10
      DEFAULT_INPUT_VBYTES: 104
      DEFAULT_OUTPUT_VBYTES: 31
      DUST_LIMIT: 546

    volumes:
      - tx_builder_data:/run/psbts
    depends_on:
      - nats
      - postgres


  middleware:
    build: ./services/middleware
    container_name: middleware
    environment:
      SERVICE_NAME: middleware

      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: btc

      NATS_URL: nats://nats:4222
      OPA_URL: http://opa:8181
      SIGNER_URL: http://10.50.0.1:8080
      DATABASE_URL: postgresql://user:pass@postgres:5432/btc

      SIGNER_HMAC_SECRET: /run/secrets/signer-hmac.secret
    depends_on:
      - nats
      - opa
    volumes:
      - ./middleware_data/wallets:/run/wallets:ro
      - ./middleware_data/secrets:/run/secrets:ro
      - ./middleware_data:/run
    ports:
    - "8080:8080"

  opa:
    image: openpolicyagent/opa:1.17.1
    container_name: opa
    command:
      - "run"
      - "--watch"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "/policies"
      - "/data"
    ports:
      - "8181:8181"
    volumes:
      - ./services/opa/policies:/policies:ro
      - ./services/opa/data:/data:ro

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"

  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    depends_on:
      - nats
    stdin_open: true
    tty: true

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: btc
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/run/postgresql/data
    - ./services/postgres/001_psbt.sql:/docker-entrypoint-initdb.d/001_psbt.sql:ro

volumes:
  tx_builder_data:
  postgres_data:
  bitcoind_data:
  middleware_data:
