services:

  tx-builder:
    build: ./services/tx-builder
    container_name: tx-builder
    environment:
      SERVICE_NAME: tx-builder
      NATS_URL: nats://nats:4222
      WORK_ROOT: /var/lib/btc-work/psbt-work

      DATABASE_URL: postgresql://user:pass@postgres:5432/btc

      BITCOIN_NETWORK: regtest
      HOT_DEPOSIT_SCRIPT_HEX: "0014aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      COLD_CHANGE_SCRIPT_HEX: "0014bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"

      BITCOIND_RPC_URL: http://bitcoind:18443
      BITCOIND_RPC_USER: user
      BITCOIND_RPC_PASS: pass
    volumes:
      - tx_builder_data:/var/lib/tx-builder
    depends_on:
      - nats
      - postgres


  middleware:
    build: ./services/middleware
    container_name: middleware
    environment:
      SERVICE_NAME: middleware
      NATS_URL: nats://nats:4222
      OPA_URL: http://opa:8181
      SIGNER_URL: http://10.50.0.1:8080
      DATABASE_URL: postgresql://user:pass@postgres:5432/btc
    depends_on:
      - nats
      - opa
    volumes:
      - ./middleware_data/wallets:/run/wallets:ro
      - ./middleware_data/secrets:/run/secrets:ro
      - ./middleware_data:/run
    ports:
    - "8080:8080"

  opa:
    image: openpolicyagent/opa:1.17.1
    container_name: opa
    command:
      - "run"
      - "--watch"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "/policies"
      - "/data"
    ports:
      - "8181:8181"
    volumes:
      - ./services/opa/policies:/policies:ro
      - ./services/opa/data:/data:ro

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"

  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    depends_on:
      - nats
    stdin_open: true
    tty: true

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: btc
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/run/postgresql/data
    - ./services/postgres/001_psbt.sql:/docker-entrypoint-initdb.d/001_psbt.sql:ro
    - ./services/postgres/002_wallet.sql:/docker-entrypoint-initdb.d/002_wallet.sql:ro

# listener:
#   build: ./services/zmq-listener
#   container_name: btc-zmq-listener
#   restart: unless-stopped
#   environment:
 #    ZMQ_ENDPOINT: "tcp://10.50.0.10:28332"
#     WHITELIST_PATH: "/data/whitelist.json"
#     NATS_URL: "nats://nats:4222"
#   volumes:
#     - ./data:/data

volumes:
  tx_builder_data:
  postgres_data:
  bitcoind_data:
  middleware_data: