apiVersion: v1
kind: Secret
metadata:
  name: btc-hot-secrets
  namespace: btc-hot
type: Opaque
stringData:
  DATABASE_URL: "postgres://USER:PASS@HOST:5432/DB?sslmode=require"

  BITCOIND_RPC_USER: "rpcuser"
  BITCOIND_RPC_PASS: "change-me-strong"

  API_TOKEN: ""